### ISSUE TITLE
Screen refreshes with each keystroke in Course Catalog search bar

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#333]
**Describe the bug**
When a user types within the search bar of the Course Catalog (Student UI), the screen refreshes with each keystroke, resulting in the screen repeatedly flashing black. (When the user types in a keyword that has been previously typed, however, screen does not refresh.)

**To Reproduce**
1. Log into UnlockEd using a student account
2. Click on Course Catalog
3. Type within the Search bar

**Expected behavior**
Screen should not flash black with each keystroke

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Firefox 129.0 (64-bit), Chrome 127.0.6533.100 (Official Build) (64-bit)

**Comment by calisio** [comment]
This is an issue with the page re-rendering on `isLoading` (in line 38 - `  if (!data) return <div></div>;`) since its calling the api each time using useSWR. Not sure if there is a better way to implement search so it doesn't re render after each key change.. it might be worth investigating. If anyone wants to pick this up in the meantime go for it - if not, I can deal with it later.
