### ISSUE TITLE
bug: if user goes directly to https://staging.unlockedlabs.xyz/{any path} and they are not logged in, they should be redirected

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#344]
**Describe the bug**
If the user goes directly to any path in our app, a 401 unauthorized error is returned and the page is blank. This should either redirect them or should show an error page that gives them the opportunity to redirect to the login page.

**To Reproduce**
1. Go to 'https://staging.unlockedlabs.xyz/dashboard' without being logged in to any account.
2. See blank page with no error - can see the 401 error in the console

**Expected behavior**
We need to show some sort of screen or redirect the user to the login page.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Additional context**
If we plan to create a new page for this, it should be sketched out on Figma first, or spoken about what the UI should look like. A discussion could be had under this issue.

**Comment by pd3000** [comment]
This should also cover this case, but adding for testing once the fix is in.

If you authenticate and leave a page past session timeout, you don't get a message that you are logged off, but you can no longer access the page and refreshing results in the same behavior documented here. Attempting to access a page you don't have an active session for should redirect you to the login screen.
