### ISSUE TITLE
User Role and Username not updating in Kratos

### ISSUE THREAD

**Issue by carddev81** [UnlockedLabs/UnlockEdv2#541]
**Describe the bug**
When updating a user's username or role in UnlockEd these fields were not being updated within Kratos user's traits. I stumbled upon this issue while mapping users from the provider user mapping screen.

**To Reproduce**
1. Log on as SuperAdmin
2. Go to Students
3. Click Edit
4. Change Username or Role

**Expected behavior**
Username or Role to be updated within the kratos identities table.

**Desktop:**
 - Microsoft Windows 11
 - Browser Chrome Version 131.0.6778.86

**Comment by PThorpe92** [comment]
Good catch! 

Discussing this on slack rn but putting this in writing for visibility. @jtucholski 

IIRC this may have been intentional, because changing the username of a student could result in them not being able to login to their provider accounts via Oauth. But this brings up an excellent point that I totally forgot, and I think the more appropriate fix here, is to make the Username and the Role fields immutable, or at least remove them from the Edit form. Since we use this field to identify our users in Provider Platforms.

We should:
1. Remove the `Role` field from the Edit Student Form (There is no situation where this would be needed going from student -> admin or vice versa, and if there was, they should just make an account).
2. Make `Username` immutable, also removing it from the student form, as this will cause problems with Oauth logins.

**Comment by calisio** [comment]
closed with #536
